### ISSUE TITLE
보유한 캐릭터 조회 기능

### ISSUE THREAD

**Issue by sj98h** [haru0726/Project_Nalgangdoo#37]
# 추가기능 요청
> 보유한 캐릭터 조회 시 별 등급도 조회가 되면 좋겠습니다

![image](https://github.com/user-attachments/assets/d29d0260-ef71-419e-a53a-fe4d4d891b7f)

## 요청사항
- [] response에 star 추가

@skyteer

**Comment by skyteer** [comment]
수정했습니다
